using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharpdxControl.Enums
{
    /// <summary>
    ///********************************************
    /// 创建人        ：  ZT
    /// 创建时间    ：  2022/10/26 11:21:11 
    /// Description   ：  
    ///********************************************/
    /// </summary>
    public enum LibraryFile
    {
        None,

        Interface1c,
        Interface,
        GameInter,
        GameInter2,
        Equip,
        EquipEffect_UI,
        EquipEffect_Part,
        ProgUse,
        StoreItems,
        Inventory,
        Ground,
        NPC,
        MiniMap,
        MagicIcon,
        CBIcon,
        QuestIcon,

        NPCImage,
        MonImage,

        PEquipB1,
        PEquipH1,

        M_Hum,
        M_HumEx1,
        M_HumEx2,
        M_HumEx3,
        M_HumEx4,
        M_HumEx10,
        M_HumEx11,
        M_HumEx12,
        M_HumEx13,
        M_Hair,

        WM_Hum,
        WM_HumEx1,
        WM_HumEx2,
        WM_HumEx3,
        WM_HumEx4,
        WM_HumEx10,
        WM_HumEx11,
        WM_HumEx12,
        WM_HumEx13,
        WM_Hair,

        M_HumA,
        M_HumAEx1,
        M_HumAEx2,
        M_HumAEx3,
        M_HairA,

        WM_HumA,
        WM_HumAEx1,
        WM_HumAEx2,
        WM_HumAEx3,
        WM_HairA,

        Horse,

        HorseIron,
        HorseSilver,
        HorseGold,
        HorseBlue,
        HorseDark,
        HorseDarkEffect,
        HorseRoyal,
        HorseRoyalEffect,

        M_Weapon1,
        M_Weapon2,
        M_Weapon3,
        M_Weapon4,
        M_Weapon5,
        M_Weapon6,
        M_Weapon7,
        M_Weapon10,
        M_Weapon11,
        M_Weapon12,
        M_Weapon13,
        M_Weapon14,
        M_Weapon15,
        M_Weapon16,

        WM_Weapon1,
        WM_Weapon2,
        WM_Weapon3,
        WM_Weapon4,
        WM_Weapon5,
        WM_Weapon6,
        WM_Weapon7,
        WM_Weapon10,
        WM_Weapon11,
        WM_Weapon12,
        WM_Weapon13,
        WM_Weapon14,
        WM_Weapon15,
        WM_Weapon16,

        M_WeaponADL1,
        M_WeaponADL2,
        M_WeaponADL6,
        M_WeaponADR1,
        M_WeaponADR2,
        M_WeaponADR6,

        M_WeaponAOH1,
        M_WeaponAOH2,
        M_WeaponAOH3,
        M_WeaponAOH4,
        M_WeaponAOH5,
        M_WeaponAOH6,

        WM_WeaponADL1,
        WM_WeaponADL2,
        WM_WeaponADL6,
        WM_WeaponADR1,
        WM_WeaponADR2,
        WM_WeaponADR6,

        WM_WeaponAOH1,
        WM_WeaponAOH2,
        WM_WeaponAOH3,
        WM_WeaponAOH4,
        WM_WeaponAOH5,
        WM_WeaponAOH6,

        M_Shield1,
        M_Shield2,

        WM_Shield1,
        WM_Shield2,

        M_Helmet1,
        M_Helmet2,
        M_Helmet3,
        M_Helmet4,
        M_Helmet5,

        M_Helmet11,
        M_Helmet12,
        M_Helmet13,
        M_Helmet14,

        WM_Helmet1,
        WM_Helmet2,
        WM_Helmet3,
        WM_Helmet4,
        WM_Helmet5,

        WM_Helmet11,
        WM_Helmet12,
        WM_Helmet13,
        WM_Helmet14,

        M_HelmetA1,
        M_HelmetA2,
        M_HelmetA3,
        M_HelmetA4,

        WM_HelmetA1,
        WM_HelmetA2,
        WM_HelmetA3,
        WM_HelmetA4,

        MonMagic,
        MonMagicEx,
        MonMagicEx2,
        MonMagicEx3,
        MonMagicEx4,
        MonMagicEx5,
        MonMagicEx6,
        MonMagicEx7,
        MonMagicEx8,
        MonMagicEx9,
        MonMagicEx19,
        MonMagicEx20,
        MonMagicEx21,
        MonMagicEx22,
        MonMagicEx23,
        MonMagicEx26,

        Mon_1,
        Mon_2,
        Mon_3,
        Mon_4,
        Mon_5,
        Mon_6,
        Mon_7,
        Mon_8,
        Mon_9,
        Mon_10,

        Mon_11,
        Mon_12,
        Mon_13,
        Mon_14,
        Mon_15,
        Mon_16,
        Mon_17,
        Mon_18,
        Mon_19,
        Mon_20,

        Mon_21,
        Mon_22,
        Mon_23,
        Mon_24,
        Mon_25,
        Mon_26,
        Mon_27,
        Mon_28,
        Mon_29,
        Mon_30,

        Mon_31,
        Mon_32,
        Mon_33,
        Mon_34,
        Mon_35,
        Mon_36,
        Mon_37,
        Mon_38,
        Mon_39,
        Mon_40,

        Mon_41,
        Mon_42,
        Mon_43,
        Mon_44,
        Mon_45,
        Mon_46,
        Mon_47,
        Mon_48,
        Mon_49,
        Mon_50,

        Mon_51,
        Mon_52,
        Mon_53,
        Mon_54,
        Mon_55,
        Mon_56,


        Magic,
        MagicEx,
        MagicEx2,
        MagicEx3,
        MagicEx4,
        MagicEx5,
        MagicEx6,
        MagicEx7,
        MagicEx8,
        MagicEx9,

        Animationsc,
        Cliffsc,
        Dungeonsc,
        Furnituresc,
        Housesc,
        Innersc,
        Object1c,
        Object2c,
        SmObjectsc,
        SmTilesc,
        Tiles5c,
        Tiles30c,
        Tilesc,
        Wallsc,

        Forest_Animationsc,
        Forest_Cliffsc,
        Forest_Dungeonsc,
        Forest_Furnituresc,
        Forest_Housesc,
        Forest_Innersc,
        Forest_SmObjectsc,
        Forest_SmTilesc,
        Forest_Tiles5c,
        Forest_Tiles30c,
        Forest_Tilesc,
        Forest_Wallsc,

        Sand_Animationsc,
        Sand_Cliffsc,
        Sand_Dungeonsc,
        Sand_Furnituresc,
        Sand_Housesc,
        Sand_Innersc,
        Sand_SmObjectsc,
        Sand_SmTilesc,
        Sand_Tiles5c,
        Sand_Tiles30c,
        Sand_Tilesc,
        Sand_Wallsc,

        Snow_Animationsc,
        Snow_Cliffsc,
        Snow_Dungeonsc,
        Snow_Furnituresc,
        Snow_Housesc,
        Snow_Innersc,
        Snow_SmObjectsc,
        Snow_SmTilesc,
        Snow_Tiles5c,
        Snow_Tiles30c,
        Snow_Tilesc,
        Snow_Wallsc,

        Wood_Animationsc,
        Wood_Cliffsc,
        Wood_Dungeonsc,
        Wood_Furnituresc,
        Wood_Housesc,
        Wood_Innersc,
        Wood_SmObjectsc,
        Wood_SmTilesc,
        Wood_Tiles5c,
        Wood_Tiles30c,
        Wood_Tilesc,
        Wood_Wallsc,
    }
}
